### PR TITLE
fix build errors with libgps 3.20 and newer

### LINKED ISSUE #38: Build fails on Ubuntu 20.04
Trying to build on Ubuntu 20.04 (Focal Fossa) ...

```
$ cmake .
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libgps'
--   Found libgps, version 3.20
-- Checking for module 'libnl-genl-3.0'
--   Found libnl-genl-3.0, version 3.4.0
-- Configuring done
-- Generating done
```

... fails with the following error:

```
[ 46%] Building C object wifi/sender/CMakeFiles/sender.dir/main.c.o
/home/janus/github/opendroneid/opendroneid-core-c/wifi/sender/main.c: In function ‘drone_adopt_gps_data’:
/home/janus/github/opendroneid/opendroneid-core-c/wifi/sender/main.c:232:36: error: invalid operands to binary * (have ‘timespec_t’ {aka ‘struct timespec’} and ‘int’)
  232 |  time_in_tenth = gpsdata->fix.time * 10;
      |                  ~~~~~~~~~~~~~~~~~ ^
      |                              |
      |                              timespec_t {aka struct timespec}
```

I assume this is due to the fact that 20.04 has the updated libgps version 3.20. On Ubuntu 18.04, with libgps version 3.17, everything works well.

### PR DESCRIPTION
**Pull request by janusw**
* fixes #38
* happens e.g. on Ubuntu 20.04
* support for older libgps versions is maintained
* depending on the libgps version, we define a preprocessor flag
  and use conditional compilation to distinguish both cases
* the TSTONS macro is taken from:
  https://gitlab.com/gpsd/gpsd/-/blob/1d4a09541a18c453c5586e6f57d3eb5fec9526ed/timespec.h#L102

### CODE REVIEW

File: wifi/sender/main.c [hunk 1]
```diff
@@ -42,6 +42,12 @@ sw@simonwunderlich.de
 
 #include <opendroneid.h>
 
+/* convert a timespec to a double.
+ * if tv_sec > 2, then inevitable loss of precision in tv_nsec
+ * so best to NEVER use TSTONS()
+ * WARNING replacing 1e9 with NS_IN_SEC causes loss of precision */
+#define TSTONS(ts) ((double)((ts)->tv_sec + ((ts)->tv_nsec / 1e9)))
```
Comment (friissoren) [inline wifi/sender/main.c:49]: I initially got confused by this since I thought 1e9 would be an integer (and thus the division would be zero almost always). However, apparently it expands to a double and everything is then good. Again I learned something :-)

**Review by friissoren — APPROVED** [review]

File: wifi/sender/main.c (hunk 1 above)
Comment (janusw) [reply wifi/sender/main.c:49]: I was actually a bit confused by the name TSTONS, since it actually gives the value in seconds, not nanoseconds. Plus, the comments and warnings are not very confidence-inspiring, either. But since this is what's used in the gpsd project, I hope it will do its duty for opendroneid as well ;)
